### ISSUE TITLE
HarrFeatures2d Dosen't work with batched Input

### ISSUE THREAD

**Issue by dr-ghost** [masadcv/PyTorchHaarFeatures#2]
If an input of torch.randn(2, 1, 128, 128) is passed to the HarrFeatures2d module. It fails

**Comment by masadcv** [comment]
What error do you get? Also what version of pytorch and python you are on?

**Comment by masadcv** [comment]
I think you have another issue that is not related to this library. 
This library is built on top of conv2d/3d from pytorch - so it should work without any issues with multiple batches. 

E.g. the following example:
```import torchhaarfeatures
import torch

haarfeat2d = torchhaarfeatures.HaarFeatures2d(kernel_size=(9, 9), stride=1)
output_haar2d = haarfeat2d(torch.rand(size=(2, 1, 128, 128)))
print(output_haar2d.shape)
```

Runs fine with outout:
`torch.Size([2, 12, 128, 128])`

I am therefore closing this
